# Generated by Django 4.2 on 2025-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_contact_profile_orderpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="cashapp_tag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="crypto_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="paypal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank", "Bank Transfer"),
                    ("paypal", "PayPal"),
                    ("cashapp", "Cash App"),
                    ("crypto", "Cryptocurrency"),
                ],
                max_length=20,
            ),
        ),
    ]
