services:
  - type: web
    name: nailshop
    runtime: python3
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn nailshop.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: nailshop
          property: host
      - key: DB_NAME
        fromDatabase:
          name: nailshop-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nailshop-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nailshop-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: nailshop-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nailshop-db
          property: port

databases:
  - name: nailshop-db
    databaseName: nailshop
    user: nailshop_user
